### PR TITLE
Feature/SC-6-user-management

### PR DESCRIPTION
**Pull request by lgaljer20**
Added user management for administrator. This feature allows admin to get list of all users, to get specific user, to change active attribute (disable or enable user to login) of specific user and to change user's role. More information can be found on [Confluence](https://mkajic20.atlassian.net/l/cp/tLHnnHqK).

Changes made:
1. Added **_BaseDTO_** that has integer that represents Id so new _**DTO**_'s can have Id's.
2. Extended existing **_UserDTO_** with **_BaseDTO_**
3. Added new types of responses: **_UsersResponseDTO_** and **_SingleUserResponseDTO_** 
4.  Implemented **_UserService_** in Business layer to handle RU (read and update) operations on users.
5.  Created **_UserController_** for user management endpoints
6.  Created unit tests for **_UserService_** and **_UserController_** to ensure that feature is working as intended.

All previous tests and newly added tests have successfully passed.

### CODE REVIEW

**Review by lraknic — APPROVED** [review]
Everything looks good. I would just add sending roleId to api/admin/users/{userId}/role if we add new role in future.

**Review by mkajic20 — APPROVED** [review]
Everything seems good, nicely done!

**Review by irosic20 — COMMENTED** [review]
Everything looks good. Keep up the job!

**Comment by lgaljer20** [comment]
@lraknic20  I agree with your comment. I missed that and I agree my code could be more maintainable. In some other sprint I will come back to this feature and try to change it. Thanks.

**Pull request merged**
