### PR TITLE
First deployment of backend

### PR DESCRIPTION
**Pull request by lgaljer20**
This pull request is the first deployment of the backend.

Our backend consists of 27 endpoints.

Card management:
-  Admin can get all cards
-  Admin can get specific card by id
-  Admin can delete specific card
-  Admin can make specific card active/inactive
-  User can get list of his cards
-  User can add new card
-  User can get specific card by id
-  User can delete card
-  User can verify card (make sure it can be used: currently not in use and active)

Charger management:
- Logged and non logged users can get list of all chargers
- Admin can create new charger
- Admin can delete charger
- Admin can edit charger details
- Admin can get specific charger by id

Event management:
- Admin or user can get user's event history 
- Admin or user can start and end charging
- Admin can get list of all past events
- Admin can get statistics for specific charger for specific date  

User management:
- Admin can get list of all users
- Admin can get info on specific user
- Admin can make specific user active or inactive
- Admin can change specific's user's role

Role management:
- Admin can get list of all roles

Login & Registration
- User can register
- User can login via email and password
- User can login with google account

### CODE REVIEW

**Review by lraknic — APPROVED** [review]
Everything is good.

**Review by tsisko20 — APPROVED** [review]
Everything is good.

**Review by mkajic20 — APPROVED** [review]
All of the required endpoints are implemented and everything works as it should.

**Review by irosic20 — APPROVED** [review]
Everything is good!

**Pull request merged**
