### PR TITLE
Implemented CORS policy to enable cross-origin requests

### PR DESCRIPTION
**Pull request by lgaljer20**
When frontend tried to use our endpoints they would get CORS problems so this problem had to be fixed immediately.

### CODE REVIEW

**Review by mkajic20 — APPROVED** [review]
I tried making a request with this change applied and everything works fine.

**Review by tsisko20 — APPROVED** [review]
It works correctly.

**Review by lraknic — APPROVED** [review]
Everything looks good.

**Review by irosic20 — APPROVED** [review]
Looks good.

**Pull request merged**
